# 📓 Label Encoding — Complete 

Is notebook mein hum `LabelEncoder` se categorical (text) data ko numbers mein convert karna seekhenge.

## 🟢 Cell 1 — Import Libraries

In [2]:
# ============================================
# IMPORT LIBRARIES
# ============================================

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

print("Libraries imported successfully!")

Libraries imported successfully!

## 🟢 Cell 2 — Create Dataset

In [3]:
# ============================================
# CREATE SAMPLE DATASET
# ============================================

data = {
    "student": ["A", "B", "C", "D", "E", "F"],
    "city": ["Delhi", "Mumbai", "Bhilai", "Delhi", "Mumbai", "Bhilai"],
    "marks": [80, 75, 90, 85, 70, 88]
}

df = pd.DataFrame(data)

df

  student    city  marks
0       A   Delhi     80
1       B  Mumbai     75
2       C  Bhilai     90
3       D   Delhi     85
4       E  Mumbai     70
5       F  Bhilai     88

## 🟢 Cell 3 — Check Data Types

In [4]:
# ============================================
# CHECK DATA TYPES
# ============================================

print(df.dtypes)

student    object
city       object
marks       int64
dtype: object

## 🟢 Cell 4 — Create Label Encoder

In [5]:
# ============================================
# CREATE LABEL ENCODER
# ============================================

encoder = LabelEncoder()

encoder

LabelEncoder()

Yahan `encoder` ek `LabelEncoder` object hai jo categories ko numbers mein convert karega.

## 🟢 Cell 5 — Apply Label Encoding

In [6]:
# ============================================
# APPLY LABEL ENCODING TO CITY
# ============================================

df["city_encoded"] = encoder.fit_transform(df["city"])

df

  student    city  marks  city_encoded
0       A   Delhi     80             1
1       B  Mumbai     75             2
2       C  Bhilai     90             0
3       D   Delhi     85             1
4       E  Mumbai     70             2
5       F  Bhilai     88             0

Possible output:

```
  student    city  marks  city_encoded
0       A   Delhi     80             1
1       B  Mumbai     75             2
2       C  Bhilai     90             0
3       D   Delhi     85             1
4       E  Mumbai     70             2
5       F  Bhilai     88             0
```

### 🔥 `fit_transform()` kya karta hai?

Ye bahut important hai.

```python
encoder.fit_transform(df["city"])
```

Actually do kaam karta hai:

**`fit()`** — Categories ko learn karta hai:

```
Bhilai
Delhi
Mumbai
```

**`transform()`** — Unko numbers mein convert karta hai:

```
Bhilai → 0
Delhi  → 1
Mumbai → 2
```

So:

```
fit_transform()
     ↓
Learn + Convert
```

## 🟢 Cell 6 — Check Mapping

In [7]:
# ============================================
# CHECK CATEGORY MAPPING
# ============================================

print("Classes:")
print(encoder.classes_)

Classes:
['Bhilai' 'Delhi' 'Mumbai']

Output:

```
['Bhilai' 'Delhi' 'Mumbai']
```

Mapping:

```
Bhilai → 0
Delhi  → 1
Mumbai → 2
```

## 🟢 Cell 7 — Manually See Mapping

In [8]:
# ============================================
# DISPLAY CATEGORY AND LABEL
# ============================================

for category, label in zip(encoder.classes_, encoder.transform(encoder.classes_)):
    print(category, "→", label)

Bhilai → 0
Delhi → 1
Mumbai → 2

Output:

```
Bhilai → 0
Delhi → 1
Mumbai → 2
```

## 🟢 Cell 8 — Convert Numbers Back

`LabelEncoder` inverse transformation bhi kar sakta hai.

In [9]:
# ============================================
# CONVERT LABELS BACK TO ORIGINAL CATEGORIES
# ============================================

df["city_original"] = encoder.inverse_transform(df["city_encoded"])

df

  student    city  marks  city_encoded city_original
0       A   Delhi     80             1         Delhi
1       B  Mumbai     75             2        Mumbai
2       C  Bhilai     90             0        Bhilai
3       D   Delhi     85             1         Delhi
4       E  Mumbai     70             2        Mumbai
5       F  Bhilai     88             0        Bhilai

Example:

```
0 → Bhilai
1 → Delhi
2 → Mumbai
```

Isko kehte hain `inverse_transform()`.

## 📌 Complete Basic Code

Agar exam/practical mein sirf Label Encoding implement karna ho:

In [10]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Create dataset
df = pd.DataFrame({
    "city": ["Delhi", "Mumbai", "Bhilai", "Delhi", "Mumbai"]
})

# Create encoder
encoder = LabelEncoder()

# Apply label encoding
df["city_encoded"] = encoder.fit_transform(df["city"])

# Display result
print(df)

# Display mapping
print("\nMapping:")
for category, label in zip(
    encoder.classes_,
    encoder.transform(encoder.classes_)
):
    print(category, "→", label)

     city  city_encoded
0   Delhi             1
1  Mumbai             2
2  Bhilai             0
3   Delhi             1
4  Mumbai             2

Mapping:
Bhilai → 0
Delhi → 1
Mumbai → 2

In [11]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["city_encoded"] = encoder.fit_transform(df["city"])