# 📓 One-Hot Encoding — Complete Jupyter Notebook

Is notebook mein hum `pd.get_dummies()` aur sklearn ke `OneHotEncoder` se categorical data ko binary columns mein convert karna seekhenge.

## 🟢 Cell 1 — Import Libraries

In [1]:
# ============================================
# IMPORT LIBRARIES
# ============================================

import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

## 🟢 Cell 2 — Create Dataset

In [2]:
# ============================================
# CREATE SAMPLE DATASET
# ============================================

data = {
    "student": ["A", "B", "C", "D", "E", "F"],
    "city": ["Delhi", "Mumbai", "Bhilai", "Delhi", "Mumbai", "Bhilai"],
    "marks": [80, 75, 90, 85, 70, 88]
}

df = pd.DataFrame(data)

df

  student    city  marks
0       A   Delhi     80
1       B  Mumbai     75
2       C  Bhilai     90
3       D   Delhi     85
4       E  Mumbai     70
5       F  Bhilai     88

## 🟢 Cell 3 — Check Categorical Columns

In [3]:
# ============================================
# CHECK CATEGORICAL COLUMNS
# ============================================

categorical_columns = df.select_dtypes(include="object").columns

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
Index(['student', 'city'], dtype='object')

Output:

```
Index(['student', 'city'], dtype='object')
```

Agar `student` sirf ID/name hai, to normally usko encode nahi karenge. Humein `city` encode karna hai.

## 🟢 Cell 4 — One-Hot Encoding using Pandas

Sabse simple method:

In [4]:
# ============================================
# APPLY ONE-HOT ENCODING
# ============================================

df_encoded = pd.get_dummies(
    df,
    columns=["city"]
)

df_encoded

  student  marks  city_Bhilai  city_Delhi  city_Mumbai
0       A     80        False        True        False
1       B     75        False       False         True
2       C     90         True       False        False
3       D     85        False        True        False
4       E     70        False       False         True
5       F     88         True       False        False

Output approximately:

```
  student  marks  city_Bhilai  city_Delhi  city_Mumbai
0       A     80         False        True        False
1       B     75         False       False         True
2       C     90          True       False        False
3       D     85         False        True        False
4       E     70         False       False         True
5       F     88          True       False        False
```

Depending on pandas version, values `True/False` ya `1/0` dikh sakti hain.

## 🟢 Cell 5 — Force 0/1

Agar specifically 0 aur 1 chahiye:

In [5]:
# ============================================
# CREATE 0/1 VALUES
# ============================================

df_encoded = pd.get_dummies(
    df,
    columns=["city"],
    dtype=int
)

df_encoded

  student  marks  city_Bhilai  city_Delhi  city_Mumbai
0       A     80            0           1            0
1       B     75            0           0            1
2       C     90            1           0            0
3       D     85            0           1            0
4       E     70            0           0            1
5       F     88            1           0            0

Ab:

```
Delhi  → city_Delhi = 1
Mumbai → city_Mumbai = 1
Bhilai → city_Bhilai = 1
```

### 🧠 `pd.get_dummies()` kya karta hai?

```python
pd.get_dummies(df, columns=["city"])
```

`city` ki unique categories find karta hai:

```
Bhilai
Delhi
Mumbai
```

Phir columns banata hai:

```
city_Bhilai
city_Delhi
city_Mumbai
```

Aur values ko:

```
1 = Present
0 = Not Present
```

mein convert karta hai.

## 🟢 Cell 6 — Single Column Encoding

Agar sirf `city` encode karna hai:

In [6]:
# ============================================
# ONE-HOT ENCODE ONLY CITY COLUMN
# ============================================

city_encoded = pd.get_dummies(
    df["city"],
    dtype=int
)

city_encoded

   Bhilai  Delhi  Mumbai
0       0      1       0
1       0      0       1
2       1      0       0
3       0      1       0
4       0      0       1
5       1      0       0

Output:

```
   Bhilai  Delhi  Mumbai
0       0       1       0
1       0       0       1
2       1       0       0
3       0       1       0
4       0       0       1
5       1       0       0
```

## 🟢 Cell 7 — Add Encoded Columns to Dataset

In [7]:
# ============================================
# COMBINE ORIGINAL DATA WITH ENCODED DATA
# ============================================

df_final = pd.concat(
    [
        df.drop("city", axis=1),
        city_encoded
    ],
    axis=1
)

df_final

  student  marks  Bhilai  Delhi  Mumbai
0       A     80       0      1       0
1       B     75       0      0       1
2       C     90       1      0       0
3       D     85       0      1       0
4       E     70       0      0       1
5       F     88       1      0       0

### 🔥 `drop("city", axis=1)` samjho

```python
df.drop("city", axis=1)
```

ka matlab: `city` column ko remove karo.

- `axis=1` means: **column**
- `axis=0` means: **row**

## 🟢 Cell 8 — One-Hot Encoding with sklearn

Machine Learning projects mein sklearn ka `OneHotEncoder` bhi use hota hai.

In [8]:
# ============================================
# IMPORT ONEHOTENCODER
# ============================================

from sklearn.preprocessing import OneHotEncoder

## 🟢 Cell 9 — Create Encoder

In [9]:
# ============================================
# CREATE ONE-HOT ENCODER
# ============================================

encoder = OneHotEncoder(
    sparse_output=False
)

`OneHotEncoder` normally sparse matrix generate kar sakta hai.

Hum `sparse_output=False` use kar rahe hain taaki normal NumPy array mile.

## 🟢 Cell 10 — Apply Encoding

In [10]:
# ============================================
# APPLY ONE-HOT ENCODING
# ============================================

encoded = encoder.fit_transform(
    df[["city"]]
)

encoded

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

Output approximately:

```
array([
    [0., 1., 0.],
    [0., 0., 1.],
    [1., 0., 0.],
    [0., 1., 0.],
    [0., 0., 1.],
    [1., 0., 0.]
])
```

## 🟢 Cell 11 — Get Feature Names

In [11]:
# ============================================
# GET ENCODED COLUMN NAMES
# ============================================

feature_names = encoder.get_feature_names_out(["city"])

print(feature_names)

['city_Bhilai' 'city_Delhi' 'city_Mumbai']

Output:

```
['city_Bhilai' 'city_Delhi' 'city_Mumbai']
```

## 🟢 Cell 12 — Convert to DataFrame

In [12]:
# ============================================
# CONVERT ENCODED DATA INTO DATAFRAME
# ============================================

encoded_df = pd.DataFrame(
    encoded,
    columns=feature_names
)

encoded_df

   city_Bhilai  city_Delhi  city_Mumbai
0          0.0         1.0          0.0
1          0.0         0.0          1.0
2          1.0         0.0          0.0
3          0.0         1.0          0.0
4          0.0         0.0          1.0
5          1.0         0.0          0.0

## 🟢 Cell 13 — Final Dataset

In [13]:
# ============================================
# CREATE FINAL DATASET
# ============================================

df_final = pd.concat(
    [
        df.drop("city", axis=1),
        encoded_df
    ],
    axis=1
)

df_final

  student  marks  city_Bhilai  city_Delhi  city_Mumbai
0       A     80          0.0         1.0          0.0
1       B     75          0.0         0.0          1.0
2       C     90          1.0         0.0          0.0
3       D     85          0.0         1.0          0.0
4       E     70          0.0         0.0          1.0
5       F     88          1.0         0.0          0.0

## ⚠️ Important: Dummy Variable Trap

Suppose:

```
city_Bhilai
city_Delhi
city_Mumbai
```

teen columns hain.

Agar:

```
city_Bhilai = 0
city_Delhi = 0
```

hai, to automatically:

```
city_Mumbai = 1
```

hai.

Isliye kabhi-kabhi ek column drop kar dete hain.

## 🟢 Cell 14 — Drop First Category

Pandas mein:

In [14]:
# ============================================
# ONE-HOT ENCODING WITH DROP FIRST
# ============================================

df_encoded = pd.get_dummies(
    df,
    columns=["city"],
    drop_first=True,
    dtype=int
)

df_encoded

  student  marks  city_Delhi  city_Mumbai
0       A     80           1            0
1       B     75           0            1
2       C     90           0            0
3       D     85           1            0
4       E     70           0            1
5       F     88           0            0

Ab 3 ke instead 2 columns milenge:

```
city_Delhi
city_Mumbai
```

`Bhilai` reference/base category ho jayegi.

## 🟢 Cell 15 — Multiple Categorical Columns

Suppose:

In [15]:
data = {
    "city": ["Delhi", "Mumbai", "Bhilai", "Delhi"],
    "gender": ["Male", "Female", "Male", "Female"],
    "marks": [80, 75, 90, 85]
}

df2 = pd.DataFrame(data)

df2

     city  gender  marks
0   Delhi    Male     80
1  Mumbai  Female     75
2  Bhilai    Male     90
3   Delhi  Female     85

Multiple columns ko ek saath encode kar sakte ho:

In [16]:
# ============================================
# ENCODE MULTIPLE CATEGORICAL COLUMNS
# ============================================

df2_encoded = pd.get_dummies(
    df2,
    columns=["city", "gender"],
    dtype=int
)

df2_encoded

   marks  city_Bhilai  city_Delhi  city_Mumbai  gender_Female  gender_Male
0     80            0           1            0              0            1
1     75            0           0            1              1            0
2     90            1           0            0              0            1
3     85            0           1            0              1            0

## 🟢 Cell 16 — Complete Practical Notebook Code

Agar practical mein complete implementation submit karna ho, ye clean version use kar sakte ho:

In [17]:
# ============================================
# ONE-HOT ENCODING - COMPLETE IMPLEMENTATION
# ============================================

import pandas as pd

# ============================================
# 1. CREATE DATASET
# ============================================

data = {
    "student": ["A", "B", "C", "D", "E", "F"],
    "city": ["Delhi", "Mumbai", "Bhilai", "Delhi", "Mumbai", "Bhilai"],
    "marks": [80, 75, 90, 85, 70, 88]
}

df = pd.DataFrame(data)

print("----- Original Dataset -----")
print(df)

# ============================================
# 2. CHECK CATEGORICAL COLUMNS
# ============================================

print("\n----- Categorical Columns -----")

categorical_columns = df.select_dtypes(
    include="object"
).columns

print(categorical_columns)

# ============================================
# 3. APPLY ONE-HOT ENCODING
# ============================================

df_encoded = pd.get_dummies(
    df,
    columns=["city"],
    dtype=int
)

# ============================================
# 4. DISPLAY ENCODED DATASET
# ============================================

print("\n----- Dataset After One-Hot Encoding -----")
print(df_encoded)

# ============================================
# 5. SAVE ENCODED DATASET
# ============================================

df_encoded.to_csv(
    "student_one_hot_encoded.csv",
    index=False
)

print("\nOne-Hot Encoding Completed Successfully!")

----- Original Dataset -----
  student    city  marks
0       A   Delhi     80
1       B  Mumbai     75
2       C  Bhilai     90
3       D   Delhi     85
4       E  Mumbai     70
5       F  Bhilai     88

----- Categorical Columns -----
Index(['student', 'city'], dtype='object')

----- Dataset After One-Hot Encoding -----
  student  marks  city_Bhilai  city_Delhi  city_Mumbai
0       A     80            0           1            0
1       B     75            0           0            1
2       C     90            1           0            0
3       D     85            0           1            0
4       E     70            0           0            1
5       F     88            1           0            0

One-Hot Encoding Completed Successfully!

## 🆚 Label Encoding vs One-Hot Encoding

| Label Encoding | One-Hot Encoding |
|---|---|
| Category → Number | Category → Multiple binary columns |
| Delhi → 0 | Delhi → [1,0,0] |
| Columns same rehte hain | Columns increase hote hain |
| Ordinal data ke liye useful | Nominal data ke liye useful |
| Artificial order create ho sakta hai | Artificial order nahi create hota |

**Example:**

Label Encoding:

```
Low    → 0
Medium → 1
High   → 2
```

Yahan order meaningful hai.

One-Hot Encoding:

```
Delhi  → 1 0 0
Mumbai → 0 1 0
Bhilai → 0 0 1
```

Yahan koi category doosri category se "greater" nahi hai.

# most importent

In [18]:
df = pd.get_dummies(
    df,
    columns=["city"],
    dtype=int
)